config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root to: 'items#index'
  resources :items
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :item_name, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :bought_at, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :login_required, only: [:index, :edit, :update, :new, :create]

  def index
    @items = current_user.items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = current_user.items.new
  end

  def create
    @item = current_user.items.new(item_params)
    
    if @item.save
      redirect_to @item, notice: "「#{@item.item_name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_url, notice: "「#{@item.item_name}」を更新しました。"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :category, :description, :price, :bought_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to items_path, notice: 'ログインしました。'
    else
      flash.now[:alert] = 'メールアドレスまたはパスワードが無効です'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to items_path, notice: 'ユーザ登録に成功しました。'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.slim
- if item.errors.present?
  ul#error_explanation
    - item.errors.full_messages.each do |message|
      li= message

= form_with model: item, local: true do |f|
  .form-group
    = f.label :item_name
    = f.text_field :item_name, class: 'form-control', id: 'item_name'
  .form-group
    = f.label :category
    = f.select :category, [['食費', '食費'],['生活用品', '生活用品'],['家賃', '家賃'],['光熱費', '光熱費'],['医療費', '医療費'],['趣味', '趣味'],['交際費', '交際費'],['サブスク', 'サブスク']], {}, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 2, class: 'form-control', id: 'description'
  .form-group
    = f.label :price
    = f.number_field :price, class: 'form-control', id: 'price'
  .form-group
    = f.label :bought_at
    = f.date_field :bought_at, class: 'form-control', id: 'bought_at'
  = f.submit nil, class: 'btn btn-primary'

app/views/items/edit.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title 購入品リストの編集
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    style
      | body {
      |   background-color: #f7f9fc;
      |   font-family: 'Arial', sans-serif;
      | }
      | .container {
      |   margin-top: 50px;
      |   max-width: 600px;
      | }
      | .form-group label {
      |   font-weight: bold;
      | }
      | .btn-primary {
      |   background-color: #007bff;
      |   border: none;
      |   padding: 10px 20px;
      |   transition: background-color 0.3s ease;
      | }
      | .btn-primary:hover {
      |   background-color: #0056b3;
      | }
      | .nav-link {
      |   display: inline;
      |   margin-bottom: 20px;
      |   color: #007bff;
      |   text-decoration: none;
      | }
      | .nav-link:hover {
      |   text-decoration: underline;
      | }
  body
    .container
      h1 購入品リストの編集

      = render partial: 'form', locals: { item: @item }

app/views/items/index.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title 購入品一覧
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    style
      | body {
      |   background-color: #f7f9fc;
      |   font-family: 'Arial', sans-serif;
      | }
      | .container {
      |   margin-top: 50px;
      |   max-width: 800px;
      | }
      | h1 {
      |   font-size: 2.5em;
      |   margin-bottom: 20px;
      | }
      | .btn-primary {
      |   background-color: #007bff;
      |   border: none;
      |   padding: 10px 20px;
      |   transition: background-color 0.3s ease;
      | }
      | .btn-primary:hover {
      |   background-color: #0056b3;
      | }
      | table {
      |   margin-top: 20px;
      |   background-color: white;
      |   border-radius: 8px;
      |   box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      | }
      | th {
      |   font-weight: bold;
      | }
      | td {
      |   vertical-align: middle;
      | }
  body
    .container
      h1 購入品一覧

      = link_to '購入品を登録する', new_item_path, class: 'btn btn-primary'

      .mb-3
      table.table.table-hover
        thead.thead-default
          tr
            th= Item.human_attribute_name(:item_name)
            th= Item.human_attribute_name(:price)
            th= Item.human_attribute_name(:bought_at)
        tbody
          - @items.each do |item|
            tr
              td= link_to item.item_name, item
              td= item.price
              td= item.bought_at

app/views/items/new.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title 新規登録
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    style
      | body {
      |   background-color: #f7f9fc;
      |   font-family: 'Arial', sans-serif;
      | }
      | .container {
      |   margin-top: 50px;
      |   max-width: 600px;
      | }
      | .form-group label {
      |   font-weight: bold;
      | }
      | .btn-primary {
      |   background-color: #007bff;
      |   border: none;
      |   padding: 10px 20px;
      |   transition: background-color 0.3s ease;
      | }
      | .btn-primary:hover {
      |   background-color: #0056b3;
      | }
      | .nav-link {
      |   display: inline;
      |   margin-bottom: 20px;
      |   color: #007bff;
      |   text-decoration: none;
      | }
      | .nav-link:hover {
      |   text-decoration: underline;
      | }
  body
    .container
      h1 新規登録

      = link_to '購入品一覧', items_path, class: 'nav-link'
      = render partial: 'form', locals: { item: @item }
      

app/views/items/show.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title 購入品詳細
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    style
      | body {
      |   background-color: #f7f9fc;
      |   font-family: 'Arial', sans-serif;
      | }
      | .container {
      |   margin-top: 50px;
      |   max-width: 800px;
      | }
      | .nav-link {
      |   display: inline;
      |   color: #007bff;
      |   text-decoration: none;
      | }
      | .nav-link:hover {
      |   text-decoration: underline;
      | }
      | h1 {
      |   font-size: 2.5em;
      |   margin-bottom: 20px;
      | }
      | table {
      |   margin-top: 20px;
      |   background-color: white;
      |   border-radius: 8px;
      |   box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      | }
      | th {
      |   font-weight: bold;
      | }
      | td {
      |   vertical-align: middle;
      | }
  body
    .container
      h1 購入品詳細

      .nav.justify-content-end
        = link_to '購入品一覧', items_path, class: 'nav-link'
      
      table.table.table-hover
        tbody
          tr
            th= Item.human_attribute_name(:item_name)
            td= @item.item_name
          tr
            th= Item.human_attribute_name(:category)
            td= @item.category
          tr
            th= Item.human_attribute_name(:description)
            td= simple_format(h(@item.description), {}, sanitize: false, wrapper_tag: "div")
          tr
            th= Item.human_attribute_name(:price)
            td= @item.price
          tr
            th= Item.human_attribute_name(:bought_at)
            td= @item.bought_at

      = link_to '編集', edit_item_path, class: 'btn btn-primary mr-3'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | 節楽
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    - if flash.notice.present?
      .alert.alert-success= flash.notice
    = yield

app/views/users/new.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title 新規登録
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    style
      | body {
      |   background-color: #f7f9fc;
      |   font-family: 'Arial', sans-serif;
      | }
      | .container {
      |   margin-top: 50px;
      |   max-width: 600px;
      | }
      | h1 {
      |   font-size: 2.5em;
      |   margin-bottom: 20px;
      | }
      | .form-control {
      |   margin-bottom: 15px;
      | }
      | .btn-primary {
      |   background-color: #007bff;
      |   border: none;
      |   padding: 10px 20px;
      |   transition: background-color 0.3s ease;
      | }
      | .btn-primary:hover {
      |   background-color: #0056b3;
      | }
      | p {
      |   margin-top: 20px;
      | }
      | a {
      |   color: #007bff;
      |   text-decoration: none;
      | }
      | a:hover {
      |   text-decoration: underline;
      | }
  body
    .container
      h1 新規登録

      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]

      .row
        .col-md-6.col-md-offset-3
          = form_for(@user) do |f|
            = f.label :name
            = f.text_field :name, class: 'form-control'

            = f.label :email
            = f.email_field :email, class: 'form-control'

            = f.label :password
            = f.password_field :password, class: 'form-control'

            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'

            = f.submit "登録", class: "btn btn-primary"

          p
            | すでにアカウントがある方はこちら
            = link_to "ログイン", login_path